Refactor search functionality
flutterph/devs pull request #302
Opened 2021-02-15 02:03 UTC by OliverRhyme

@joshuadeguzman 
Refactors the search functionality with the flexibility to easily integrate Jobs search.
Add Developer loading

2021-02-15 02:08 UTC, OliverRhyme commented on lib/features/devboard/devboard_page.dart
> +class DevProgress extends StatelessWidget {
Improve the design of this

2021-02-15 02:28 UTC, joshuadeguzman commented
Hello @OliverRhyme,

Few things from me,
- Please add the screenshots for the changes made (preferably GIF or video?)
- Please rebase to the latest commit

Thanks for this.

2021-02-15 02:29 UTC, OliverRhyme commented
> Hello @OliverRhyme,
> 
> Few things from me,
> 
> * Please add the screenshots for the changes made (preferably GIF or video?)
> * Create issue tickets for the changes you made, eg. create an issue for refactoring search
> * Please rebase to the latest commit
> 
> Thanks for this.

I am able to run the page on my github fork at [https://oliverrhyme.github.io/devs](url)

2021-02-15 02:36 UTC, joshuadeguzman requested changes
Hello @OliverRhyme,

Thanks for the PR. 🎉 

Kindly review the comments. For the meantime, let's ignore issues that are not related to the PR, eg. providing repository and data source, to keep the PR small as possible.

cc: @ram231  @Jansalvador1445

2021-02-15 02:36 UTC, joshuadeguzman commented on .all-contributorsrc
> +    },
Please rebase to the latest master branch :D

2021-02-15 02:36 UTC, joshuadeguzman commented on lib/core/widgets/components/search_bar.dart
> +            hintText: "Who are you looking for?",
I recommend not changing this one for now.

2021-02-15 02:36 UTC, joshuadeguzman commented on lib/features/dashboard/dashboard_model.dart
> +                  // TODO: Improve null safety efficiency, maybe utilizing extension function
Kindly create an issue ticket to migrate this to a utility or extension.

2021-02-15 02:36 UTC, joshuadeguzman commented on lib/features/dashboard/dashboard_model.dart
> +    // TODO: Add a switch statement to handle stream switching when selecting page
Are you adding it on a follow up PR?

2021-02-15 02:36 UTC, joshuadeguzman commented on lib/features/dashboard/dashboard_page.dart
> +      // MultiProvider(
Let's stick with MultiProvider to avoid unnecessary changes when adding or removing more providers.

2021-02-15 02:36 UTC, joshuadeguzman commented on lib/features/devboard/devboard_page.dart
> +    devBoardModel =  Provider.of(context, listen: false);
`context` here is not available upon initialising the widget before first render.

Please see [this](https://stackoverflow.com/questions/60343605/how-to-use-data-from-provider-during-initstate-in-flutter-application) or maintain the initialisation in `didChangeDependencies`

2021-02-15 02:36 UTC, joshuadeguzman commented on lib/features/devboard/devboard_page.dart
> +class DevProgress extends StatelessWidget {
Please create an issue ticket for this. Thank you @OliverRhyme

2021-02-15 02:36 UTC, joshuadeguzman commented on lib/main.dart
> +        // No need to expose the sources
Please ignore this for now.

2021-02-15 02:58 UTC, OliverRhyme commented on lib/features/devboard/devboard_page.dart
> +    devBoardModel =  Provider.of(context, listen: false);
Its weird that following the StackOverflow instead breaks the code, but the this method works and also the `didChangeDependencies` method. Anyway will revert back to `didChangeDependencies`, thank you.

2021-02-15 03:04 UTC, OliverRhyme commented on lib/features/dashboard/dashboard_page.dart
> +      // MultiProvider(
Noted thank you.

2021-02-15 03:05 UTC, OliverRhyme commented on lib/features/dashboard/dashboard_model.dart
> +    // TODO: Add a switch statement to handle stream switching when selecting page
Just an idea for whoever works on jobs page in the future.

2021-02-15 03:19 UTC, OliverRhyme commented on .all-contributorsrc
> +    },
Done rebasing thank you.

2021-02-15 03:30 UTC, OliverRhyme commented
> Hello @OliverRhyme,
> 
> Thanks for the PR. 🎉
> 
> Kindly review the comments. For the meantime, let's ignore issues that are not related to the PR, eg. providing repository and data source, to keep the PR small as possible.
> 
> cc: @ram231 @Jansalvador1445

I've just refactored, as it is needed for the search to work properly

2021-02-15 04:36 UTC, OliverRhyme commented
Separated dev loading indicator into another pull request

2021-02-16 14:05 UTC, OliverRhyme commented
Hi po @joshuadeguzman @Jansalvador1445 pa review po. I've already addressed some of the concerns.

Note: This will overwrite the #282 since its not compatible, but I have my own implementation with the follow up PR which can easily be improved.

2021-02-16 23:04 UTC, ram231 commented on lib/utils/utils.dart
> +    return this == null ? false : this.toLowerCase().contains(other.toLowerCase());
It can be rewritten as `this?.toLowerCase()?.contains(other.toLowerCase()) ?? false;` but it does the same thing. You can practice it on your own to make less ternary statement less complicated. well anyways, LGTM.

2021-02-16 23:06 UTC, ram231 approved these changes
![LGTM](https://blog.alexv525.com/wp-content/uploads/2020/08/LGTM.png)

2021-02-17 00:05 UTC, OliverRhyme commented on lib/utils/utils.dart
> +    return this == null ? false : this.toLowerCase().contains(other.toLowerCase());
Yes I forgot to improve this when im debugging the null safety, anyway I have a follow-up PR. Thank you.

2021-02-23 11:45 UTC, merged

2021-02-23 11:45 UTC, joshuadeguzman commented
@all-contributors please add @OliverRhyme  for code, bug

2021-02-23 11:46 UTC, joshuadeguzman approved these changes